(package-refresh-contents)
(package-install 'zenburn-theme)
(package-install 'monokai-theme)
(package-install 'material-theme)
(package-install 'haskell-mode)
(package-install 'ghc)
(package-install 'company-ghc)
(package-install 'smex)
(package-install 'yasnippet)
(package-install 'smart-mode-line)
(package-install 'smart-mode-line-powerline-theme)
(package-install 'rainbow-delimiters)

